### ISSUE TITLE
Seeking help for installing MacOS in HP Victus 16

### ISSUE THREAD

**Issue by sagarsen2023** [puneetred/Victus-5600H-5500M-Hackintosh#1]
Hello! I have HP victus with Ryzen 5 5600H and RX 5500M. Can you help me to do a successful installation of macOS please?

**Comment by cosmicwanderer7** [comment]
+1

**Comment by puneetred** [comment]
I'd recommend following the [Dortania's OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/) for a comprehensive walkthrough. Additionally, check out the [Noot Hackintosh Guide](https://chefkissinc.github.io/guide) for AMD-specific patches. These guides are incredibly detailed and should be more helpful than anything I could write myself. Good luck with your installation!

**Comment by sagarsen2023** [comment]
Hi!. I have successfully booted into macos sonoma but my wifi card is not supporting and also have some trackpad issue. Single Tap not working in this efi. How can I fix that? Do I need to buy another wifi card of intel?

**Comment by puneetred** [comment]
Hello there! Great to hear that you've successfully booted into macOS Sonoma. Regarding the Wi-Fi card issue, unfortunately, Realtek cards are not supported, and obtaining Bluetooth functionality for some Realtek cards using `BlueToolFixup.kext` from [acidanthera/BrcmPatchRAM](https://github.com/acidanthera/BrcmPatchRAM) has been reported by some users, but success may vary. In my case, I couldn't make it work and opted to use ethernet and tethering for internet access.

As for the trackpad issue with single tap not working properly, it seems like the touch registration requires a slightly longer tap duration. I haven't found a specific fix for this yet, and I personally use external mice to bypass the inconvenience.

**Comment by sagarsen2023** [comment]
Thank you so much for your reply. I have one more question. I just have the igpu to work and that used to get the laptop display. Now I wonder, if i use davinci resolve(which requires a dGPU), can I use that? I mean will dgpu do the computing if needed? I do not need the display output from that...

**Comment by 1bye** [comment]
> Thank you so much for your reply. I have one more question. I just have the igpu to work and that used to get the laptop display. Now I wonder, if i use davinci resolve(which requires a dGPU), can I use that? I mean will dgpu do the computing if needed? I do not need the display output from that... 

Hello! I'm also interested in installing MacOS on my Victus 16. Did you modify the kexts or EFI config of this GitHub project?

**Comment by sagarsen2023** [comment]
> > Thank you so much for your reply. I have one more question. I just have the igpu to work and that used to get the laptop display. Now I wonder, if i use davinci resolve(which requires a dGPU), can I use that? I mean will dgpu do the computing if needed? I do not need the display output from that...
> 
> Hello! I'm also interested in installing MacOS on my Victus 16. Did you modify the kexts or EFI config of this GitHub project?

No I didn't.
